# golangci-lint configuration
# This file configures the golangci-lint tool for the GoPCA project
# Requires golangci-lint v1.50.0 or later

run:
  # Timeout for analysis
  timeout: 5m
  
  # Modules download mode
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - misspell
  disable:
    - gocritic  # Too opinionated for initial setup
    - revive    # Conflicts with gocritic

linters-settings:
  govet:
    enable:
      - shadow

issues:
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - errcheck
        - dupl
  
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 10
  
  # Show only new issues in pull requests
  new: false