# golangci-lint configuration
# This file configures the golangci-lint tool for the GoPCA project

run:
  # Timeout for analysis
  timeout: 5m
  
  # Modules download mode
  modules-download-mode: readonly
  
  # Exclude directories using issues configuration instead
  # as skip-dirs is deprecated

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - goimports
    - revive
    - misspell

linters-settings:
  govet:
    enable:
      - shadow
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  # Exclude desktop package from all linters
  exclude-dirs:
    - cmd/gopca-desktop
  
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - errcheck
        - dupl
    - path: cmd/gopca-desktop
      linters:
        - typecheck
        - unused
  
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 10
  
  # Show only new issues in pull requests
  new: false