# golangci-lint configuration for GoPCA
# This configuration ensures consistent code quality across the project
# Compatible with golangci-lint v1.x (CI uses v1.61.0)

run:
  timeout: 5m
  # Skip the desktop package during CI builds
  # The desktop package requires Wails and special build tags
  skip-dirs:
    - cmd/gopca-desktop

linters:
  disable-all: true
  enable:
    # Essential linters for code quality
    - errcheck     # Check for unchecked errors
    - gosimple     # Simplify code
    - govet        # Reports suspicious constructs
    - ineffassign  # Detects ineffectual assignments
    - staticcheck  # Advanced static analysis
    - typecheck    # Type checking
    - unused       # Find unused code
    
    # Code style and formatting
    - gofmt        # Format code
    - goimports    # Manage imports
    
    # Best practices
    - gosec        # Security issues
    - unconvert    # Unnecessary type conversions
    - unparam      # Unused function parameters
    - misspell     # Spell checker
    
    # Additional quality checks
    - bodyclose    # Check HTTP response body is closed
    - dupl         # Code duplication
    - goconst      # Find repeated constants
    - gocritic     # Various opinionated checks
    - gocyclo      # Cyclomatic complexity
    - nakedret     # Naked returns
    - whitespace   # Trailing whitespace

linters-settings:
  errcheck:
    # Check for errors in type assertions: `a := b.(MyStruct)`
    check-type-assertions: true
    # Check for errors in blank assignments: `num, _ := strconv.Atoi(numStr)`
    check-blank: false
  
  govet:
    # Report about shadowed variables
    check-shadowing: true
  
  gocyclo:
    # Minimal code complexity to report, default is 30
    min-complexity: 15
  
  dupl:
    # Tokens count to trigger issue, default is 150
    threshold: 100
  
  goconst:
    # Minimal length of string constant
    min-len: 3
    # Minimal occurrences count to trigger
    min-occurrences: 3

issues:
  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - gosec
        
    # Exclude lll issues for long lines with //go:generate
    - linters:
        - lll
      source: "^//go:generate "