// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadIrisDataset():Promise<main.FileData>;

export function ParseCSV(arg1:string):Promise<main.FileData>;

export function RunPCA(arg1:main.PCARequest):Promise<main.PCAResponse>;
