// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadIrisDataset() {
  return window['go']['main']['App']['LoadIrisDataset']();
}

export function ParseCSV(arg1) {
  return window['go']['main']['App']['ParseCSV'](arg1);
}

export function RunPCA(arg1) {
  return window['go']['main']['App']['RunPCA'](arg1);
}
