// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetVersion():Promise<string>;

export function LoadCSV(arg1:string):Promise<main.FileData>;

export function SaveCSV(arg1:main.FileData):Promise<void>;

export function ValidateForGoPCA(arg1:main.FileData):Promise<main.ValidationResult>;
