// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadCSV(arg1) {
  return window['go']['main']['App']['LoadCSV'](arg1);
}

export function SaveCSV(arg1) {
  return window['go']['main']['App']['SaveCSV'](arg1);
}

export function SaveExcel(arg1) {
  return window['go']['main']['App']['SaveExcel'](arg1);
}

export function ValidateForGoPCA(arg1) {
  return window['go']['main']['App']['ValidateForGoPCA'](arg1);
}
