// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDataQuality(arg1) {
  return window['go']['main']['App']['AnalyzeDataQuality'](arg1);
}

export function AnalyzeMissingValues(arg1) {
  return window['go']['main']['App']['AnalyzeMissingValues'](arg1);
}

export function ApplyTransformation(arg1, arg2) {
  return window['go']['main']['App']['ApplyTransformation'](arg1, arg2);
}

export function CheckGoPCAStatus() {
  return window['go']['main']['App']['CheckGoPCAStatus']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DownloadGoPCA() {
  return window['go']['main']['App']['DownloadGoPCA']();
}

export function ExecuteCellEdit(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteCellEdit'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteDeleteColumns(arg1, arg2) {
  return window['go']['main']['App']['ExecuteDeleteColumns'](arg1, arg2);
}

export function ExecuteDeleteRows(arg1, arg2) {
  return window['go']['main']['App']['ExecuteDeleteRows'](arg1, arg2);
}

export function ExecuteDuplicateRows(arg1, arg2) {
  return window['go']['main']['App']['ExecuteDuplicateRows'](arg1, arg2);
}

export function ExecuteFillMissingValues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteFillMissingValues'](arg1, arg2, arg3, arg4);
}

export function ExecuteHeaderEdit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteHeaderEdit'](arg1, arg2, arg3, arg4);
}

export function ExecuteInsertColumn(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteInsertColumn'](arg1, arg2, arg3);
}

export function ExecuteInsertRow(arg1, arg2) {
  return window['go']['main']['App']['ExecuteInsertRow'](arg1, arg2);
}

export function ExecuteToggleTargetColumn(arg1, arg2) {
  return window['go']['main']['App']['ExecuteToggleTargetColumn'](arg1, arg2);
}

export function FillMissingValues(arg1, arg2) {
  return window['go']['main']['App']['FillMissingValues'](arg1, arg2);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetTransformableColumns(arg1, arg2) {
  return window['go']['main']['App']['GetTransformableColumns'](arg1, arg2);
}

export function GetUndoRedoState() {
  return window['go']['main']['App']['GetUndoRedoState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportFile(arg1, arg2) {
  return window['go']['main']['App']['ImportFile'](arg1, arg2);
}

export function LoadCSV(arg1) {
  return window['go']['main']['App']['LoadCSV'](arg1);
}

export function OpenInGoPCA(arg1) {
  return window['go']['main']['App']['OpenInGoPCA'](arg1);
}

export function PreviewFile(arg1, arg2) {
  return window['go']['main']['App']['PreviewFile'](arg1, arg2);
}

export function Redo() {
  return window['go']['main']['App']['Redo']();
}

export function SaveCSV(arg1) {
  return window['go']['main']['App']['SaveCSV'](arg1);
}

export function SaveExcel(arg1) {
  return window['go']['main']['App']['SaveExcel'](arg1);
}

export function SelectFileForImport() {
  return window['go']['main']['App']['SelectFileForImport']();
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function ValidateForGoPCA(arg1) {
  return window['go']['main']['App']['ValidateForGoPCA'](arg1);
}
