// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeDataQuality(arg1:main.FileData):Promise<main.DataQualityReport>;

export function AnalyzeMissingValues(arg1:main.FileData):Promise<main.MissingValueStats>;

export function CheckGoPCAStatus():Promise<main.GoPCAStatus>;

export function DownloadGoPCA():Promise<void>;

export function FillMissingValues(arg1:main.FileData,arg2:main.FillMissingValuesRequest):Promise<main.FileData>;

export function GetVersion():Promise<string>;

export function LoadCSV(arg1:string):Promise<main.FileData>;

export function OpenInGoPCA(arg1:main.FileData):Promise<void>;

export function SaveCSV(arg1:main.FileData):Promise<void>;

export function SaveExcel(arg1:main.FileData):Promise<void>;

export function ValidateForGoPCA(arg1:main.FileData):Promise<main.ValidationResult>;
