// GoPCA Suite
//
// Copyright © 2025-2026 Rune Mathisen <devel@bitjungle.com>
//
// This file is part of GoPCA Suite.
//
// GoPCA Suite is source-available software with free binary redistribution.
// Official compiled binary releases may be used and redistributed free of charge
// under the GoPCA Suite Source-Available Freeware License.
//
// The source code is provided for viewing, review, education, security analysis,
// research, interoperability analysis, and evaluation only.
//
// Modification, redistribution, publication, sublicensing, reuse, incorporation
// into another project, or creation of derivative works based on the source code
// is not permitted without prior written permission from the copyright holder.
//
// Usage Restriction: GoPCA Suite may not be used, directly or indirectly, for
// military, warfare, weapons, intelligence, surveillance, targeting, or
// law-enforcement surveillance applications.
//
// See LICENSE for the full license terms.

package transform

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"testing"
)

// clrReferencePath is written by testdata/validation/generate_clr_reference.py.
const clrReferencePath = "../../testdata/validation/reference_results/clr_reference.json"

type clrReferenceCase struct {
	Input   [][]float64 `json:"input"`
	CLR     [][]float64 `json:"clr"`
	RowSums []float64   `json:"row_sums"`
}

// requireCLRReference skips locally with instructions and fails in CI.
//
// Skipping everywhere is how a comparison silently stops running: the suite
// stays green while validating nothing. CI has no excuse for the file being
// absent, because the workflow generates it before the tests.
func requireCLRReference(t *testing.T) map[string]clrReferenceCase {
	t.Helper()

	raw, err := os.ReadFile(clrReferencePath)
	if os.IsNotExist(err) {
		if os.Getenv("CI") != "" {
			t.Fatalf("the CLR reference file is missing in CI (%s). It is generated by "+
				".github/workflows/build.yml before the tests run, so this means the "+
				"generation step failed or the generator was dropped from that list.",
				filepath.Base(clrReferencePath))
		}
		t.Skipf("CLR reference not generated. Run:\n" +
			"  cd testdata && source .venv/bin/activate && cd validation \\\n" +
			"    && python generate_clr_reference.py && cd ../.. && deactivate")
	}
	if err != nil {
		t.Fatalf("reading the CLR reference: %v", err)
	}

	var reference map[string]clrReferenceCase
	if err := json.Unmarshal(raw, &reference); err != nil {
		t.Fatalf("parsing the CLR reference: %v", err)
	}
	if len(reference) == 0 {
		t.Fatal("the CLR reference is empty, so this test is passing by not looking")
	}
	return reference
}

// clrInputFor builds a transform Input from a numeric matrix.
func clrInputFor(matrix [][]float64) (Input, []string) {
	names := make([]string, len(matrix[0]))
	for j := range names {
		names[j] = fmt.Sprintf("p%d", j+1)
	}

	data := make([][]string, len(matrix))
	for i, row := range matrix {
		cells := make([]string, len(row))
		for j, value := range row {
			cells[j] = strconv.FormatFloat(value, 'g', 17, 64)
		}
		data[i] = cells
	}

	types := make(map[string]string, len(names))
	for _, name := range names {
		types[name] = "numeric"
	}

	return Input{
		Data:        data,
		Headers:     append([]string(nil), names...),
		ColumnTypes: types,
		Rows:        len(matrix),
		Columns:     len(names),
	}, names
}

// TestValidateCLRAgainstReference compares the transform against values
// computed independently in numpy.
//
// The generator forms the geometric mean as a product and divides; the Go code
// subtracts the mean of the logarithms. Those are the same quantity by
// identity, and computing it two different ways is what makes this a check
// rather than a restatement of the implementation.
func TestValidateCLRAgainstReference(t *testing.T) {
	reference := requireCLRReference(t)

	const tolerance = 1e-9

	for name, want := range reference {
		t.Run(name, func(t *testing.T) {
			in, names := clrInputFor(want.Input)

			res, err := Apply(in, Options{Type: CLR, Columns: names})
			if err != nil {
				t.Fatalf("Apply CLR: %v", err)
			}

			for j, colName := range names {
				index := findColumn(res.Headers, colName+"_clr")
				if index == -1 {
					t.Fatalf("no column %s_clr in %v", colName, res.Headers)
				}
				for i := range want.CLR {
					got, err := strconv.ParseFloat(res.Data[i][index], 64)
					if err != nil {
						t.Fatalf("row %d column %s: %v", i, colName, err)
					}
					if diff := math.Abs(got - want.CLR[i][j]); diff > tolerance {
						t.Errorf("row %d part %d: got %.12g, numpy gives %.12g (diff %.3g)",
							i, j, got, want.CLR[i][j], diff)
					}
				}
			}
		})
	}
}

// TestCLRRowsSumToZero asserts the defining property rather than the values.
//
// Every clr row sums to zero by construction, because each part is measured
// against the mean of the logarithms. A wrong mean -- over the columns instead
// of the row, say -- reproduces plausible-looking numbers that fail this.
func TestCLRRowsSumToZero(t *testing.T) {
	reference := requireCLRReference(t)

	for name, want := range reference {
		t.Run(name, func(t *testing.T) {
			in, names := clrInputFor(want.Input)
			res, err := Apply(in, Options{Type: CLR, Columns: names})
			if err != nil {
				t.Fatalf("Apply CLR: %v", err)
			}

			for i := range want.Input {
				total := 0.0
				for _, colName := range names {
					index := findColumn(res.Headers, colName+"_clr")
					value, err := strconv.ParseFloat(res.Data[i][index], 64)
					if err != nil {
						t.Fatalf("row %d: %v", i, err)
					}
					total += value
				}
				if math.Abs(total) > 1e-9 {
					t.Errorf("row %d sums to %.3g, want 0", i, total)
				}
			}
		})
	}
}

// TestCLRIsScaleInvariant is the property that says clr describes ratios.
//
// A row and the same row multiplied by any constant must transform to
// identical values, because the constant cancels between the part and the
// geometric mean. An implementation that centred on the arithmetic mean, or
// forgot to divide by the geometric one, would fail this while still producing
// numbers that look reasonable.
func TestCLRIsScaleInvariant(t *testing.T) {
	base := [][]float64{{2, 3, 5}}
	scaled := [][]float64{{2000, 3000, 5000}}

	transform := func(matrix [][]float64) []float64 {
		in, names := clrInputFor(matrix)
		res, err := Apply(in, Options{Type: CLR, Columns: names})
		if err != nil {
			t.Fatalf("Apply CLR: %v", err)
		}
		out := make([]float64, len(names))
		for j, colName := range names {
			index := findColumn(res.Headers, colName+"_clr")
			value, err := strconv.ParseFloat(res.Data[0][index], 64)
			if err != nil {
				t.Fatalf("%v", err)
			}
			out[j] = value
		}
		return out
	}

	a, b := transform(base), transform(scaled)
	for j := range a {
		if math.Abs(a[j]-b[j]) > 1e-12 {
			t.Errorf("part %d: %.12g against %.12g — clr must be scale invariant",
				j, a[j], b[j])
		}
	}
}
