// GoPCA Suite
//
// Copyright © 2025-2026 Rune Mathisen <devel@bitjungle.com>
//
// This file is part of GoPCA Suite.
//
// GoPCA Suite is source-available software with free binary redistribution.
// Official compiled binary releases may be used and redistributed free of charge
// under the GoPCA Suite Source-Available Freeware License.
//
// The source code is provided for viewing, review, education, security analysis,
// research, interoperability analysis, and evaluation only.
//
// Modification, redistribution, publication, sublicensing, reuse, incorporation
// into another project, or creation of derivative works based on the source code
// is not permitted without prior written permission from the copyright holder.
//
// Usage Restriction: GoPCA Suite may not be used, directly or indirectly, for
// military, warfare, weapons, intelligence, surveillance, targeting, or
// law-enforcement surveillance applications.
//
// See LICENSE for the full license terms.

package transform

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"testing"
)

const powerReferencePath = "../../testdata/validation/reference_results/power_transform_reference.json"

type powerReferenceCase struct {
	Input        []float64            `json:"input"`
	FittedLambda float64              `json:"fitted_lambda"`
	AtLambda     map[string][]float64 `json:"at_lambda"`
}

func requirePowerReference(t *testing.T) map[string]map[string]powerReferenceCase {
	t.Helper()

	raw, err := os.ReadFile(powerReferencePath)
	if os.IsNotExist(err) {
		if os.Getenv("CI") != "" {
			t.Fatalf("the power transform reference is missing in CI (%s). It is "+
				"generated by .github/workflows/build.yml before the tests run, so "+
				"this means the generation step failed or the generator was dropped "+
				"from that list.", filepath.Base(powerReferencePath))
		}
		t.Skipf("power transform reference not generated. Run:\n" +
			"  cd testdata && source .venv/bin/activate && cd validation \\\n" +
			"    && python generate_power_transform_reference.py && cd ../.. && deactivate")
	}
	if err != nil {
		t.Fatalf("reading the power transform reference: %v", err)
	}

	var reference map[string]map[string]powerReferenceCase
	if err := json.Unmarshal(raw, &reference); err != nil {
		t.Fatalf("parsing the power transform reference: %v", err)
	}
	if len(reference) == 0 {
		t.Fatal("the reference is empty, so this test is passing by not looking")
	}
	return reference
}

func powerInputFor(values []float64) Input {
	data := make([][]string, len(values))
	for i, value := range values {
		data[i] = []string{strconv.FormatFloat(value, 'g', 17, 64)}
	}
	return Input{
		Data:        data,
		Headers:     []string{"X"},
		ColumnTypes: map[string]string{"X": "numeric"},
		Rows:        len(values),
		Columns:     1,
	}
}

func powerResults(t *testing.T, res *Result) []float64 {
	t.Helper()
	out := make([]float64, 0, len(res.Data))
	for _, row := range res.Data {
		value, err := strconv.ParseFloat(row[0], 64)
		if err != nil {
			t.Fatalf("parsing %q: %v", row[0], err)
		}
		out = append(out, value)
	}
	return out
}

// TestValidatePowerTransformAtGivenLambda checks the formula against scipy.
//
// Lambda is supplied rather than fitted, so this isolates the closed-form
// expression from the search that finds lambda. Both sides evaluate the same
// definition, so the tolerance is tight -- loosened only by the six
// significant figures the results are written with.
func TestValidatePowerTransformAtGivenLambda(t *testing.T) {
	reference := requirePowerReference(t)

	for _, spec := range []struct {
		key       string
		transform Type
	}{
		{"boxcox", BoxCox},
		{"yeojohnson", YeoJohnson},
	} {
		cases, ok := reference[spec.key]
		if !ok || len(cases) == 0 {
			t.Fatalf("no %s cases in the reference", spec.key)
		}

		for name, want := range cases {
			for lambdaText, expected := range want.AtLambda {
				t.Run(fmt.Sprintf("%s/%s/lambda=%s", spec.key, name, lambdaText), func(t *testing.T) {
					lambda, err := strconv.ParseFloat(lambdaText, 64)
					if err != nil {
						t.Fatalf("bad lambda key %q", lambdaText)
					}

					res, err := Apply(powerInputFor(want.Input), Options{
						Type: spec.transform, Columns: []string{"X"}, Lambda: &lambda,
					})
					if err != nil {
						t.Fatalf("Apply: %v", err)
					}
					got := powerResults(t, res)

					for i := range expected {
						// Results are written with six significant figures, so
						// the comparison is relative to the magnitude rather
						// than absolute -- these values span many orders.
						scale := math.Max(1, math.Abs(expected[i]))
						if diff := math.Abs(got[i] - expected[i]); diff > 1e-5*scale {
							t.Fatalf("row %d: got %.10g, scipy gives %.10g (diff %.3g)",
								i, got[i], expected[i], diff)
						}
					}
				})
			}
		}
	}
}

// TestValidateFittedLambdaAgainstScipy checks the search, not the formula.
//
// scipy maximises the same profile likelihood with Brent; this uses
// golden-section search. They should agree on where the maximum is, not on the
// arithmetic that found it, so the tolerance reflects agreement about a
// location rather than about a computation.
//
// Comparing only the transformed output would leave a correct formula with a
// mis-converging search indistinguishable from the reverse, which is why this
// is a separate test.
func TestValidateFittedLambdaAgainstScipy(t *testing.T) {
	reference := requirePowerReference(t)

	for _, spec := range []struct {
		key       string
		transform Type
	}{
		{"boxcox", BoxCox},
		{"yeojohnson", YeoJohnson},
	} {
		for name, want := range reference[spec.key] {
			t.Run(spec.key+"/"+name, func(t *testing.T) {
				got := estimateLambda(want.Input, spec.transform)
				if diff := math.Abs(got - want.FittedLambda); diff > 1e-3 {
					t.Errorf("fitted λ = %.6f, scipy fits %.6f (diff %.3g)",
						got, want.FittedLambda, diff)
				}
			})
		}
	}
}
