#!/bin/bash
#
# test-core.sh - Run tests for core GoPCA packages
#
# This script runs tests excluding the desktop package which requires
# frontend build artifacts that may not be available during testing.

set -e

echo "=== Running Core GoPCA Tests ==="

# Show Go version
echo "Go version: $(go version)"

# Download dependencies (module graph is already tidy from the CI workflow step)
echo "Downloading dependencies..."
go mod download

# Run tests with proper exclusions
echo "Running root-module tests..."

# The package list is derived, not maintained by hand.
#
# It used to be spelled out here, and it fell behind: internal/integration,
# pkg/security and pkg/utils held ten test files between them that CI had never
# once run. Nothing reported that, because a list of packages cannot tell you
# about the package it does not mention. A new package joined the build, joined
# the repository, and simply never joined this line.
#
# `go list` selects packages that actually have test files, which is what the
# hand-written list was reaching for: naming a package with no tests is what
# caused the Windows CI trouble the old comment referred to. Now that property
# is enforced rather than remembered.
#
# Note: cmd/gocsv is a separate Go module whose full test suite runs below (#751);
# its tests are headless (httptest + pure logic, no live Wails context).

# Create minimal frontend/dist for GoPCA Desktop tests (avoids embed errors).
# This has to happen before `go list`, which parses every package including the
# one with the //go:embed directive.
mkdir -p cmd/gopca-desktop/frontend/dist
echo '<!DOCTYPE html><html><body>Test</body></html>' > cmd/gopca-desktop/frontend/dist/index.html

# node_modules is excluded by path. `go list ./...` really does descend into it:
# flatted ships a Go implementation, and it sits inside this module's tree, so it
# is a package as far as Go is concerned. It has no tests today and would be
# filtered out on that ground alone, but relying on a third-party package never
# growing a test file is not a rule, it is a hope.
CORE_PACKAGES=$(go list -f '{{if or .TestGoFiles .XTestGoFiles}}{{.ImportPath}}{{end}}' ./... \
    | grep -v '/node_modules/' \
    | tr '\n' ' ')

if [ -z "$CORE_PACKAGES" ]; then
    echo "✗ No packages with tests were found, which cannot be right"
    exit 1
fi

# Print what will run. A derived list is only an improvement if it is visible:
# a package silently dropping out of it should be as obvious as one silently
# never joining was not.
echo "Testing $(echo "$CORE_PACKAGES" | wc -w | tr -d ' ') packages with test files:"
echo "$CORE_PACKAGES" | tr ' ' '\n' | sed '/^$/d' | sed 's|^github.com/bitjungle/gopca|  .|'
echo ""

# shellcheck disable=SC2086
if ! go test -v -cover $CORE_PACKAGES; then
    echo "✗ Core tests failed"
    exit 1
fi

# The scikit-learn comparison is a developer check, not a CI gate, and it is
# worth being blunt about that rather than leaving it looking like one.
#
# It runs only when testdata/validation/reference_results exists. That directory
# is gitignored and generated by testdata/validation/generate_reference_*.py,
# which needs numpy, pandas and scikit-learn — none of which the CI image has. So
# on CI this branch is never taken, and even when it is taken a failure only
# prints. Nothing here can turn the build red.
#
# That is a defensible position: the comparison needs a Python toolchain and a
# generation step, and the mathematics it checks is also pinned by the algebraic
# identities in internal/core, which do run here. But it must not be mistaken for
# enforcement, so the output says which of the two it is.
if [ -d "testdata/validation/reference_results" ]; then
    echo ""
    echo "=== Running scikit-learn validation (developer check, does not gate) ==="
    if ! go test -v -timeout 10m ./internal/core -run "TestValidate|TestNIPALS|TestMath"; then
        echo "✗ scikit-learn validation FAILED — investigate before releasing."
        echo "  Not failing the build: this step is advisory by design (#836)."
    else
        echo "✓ scikit-learn validation passed"
    fi
else
    echo ""
    echo "Note: scikit-learn validation skipped — no reference results present."
    echo "  Generate them with testdata/validation/generate_reference_*.py."
    echo "  This step never runs on CI; it is a developer check (#836)."
fi

# Then run the full GoCSV module suite (separate module; headless tests — #751)
cd cmd/gocsv

# Create minimal frontend/dist for GoCSV tests (avoids embed errors)
mkdir -p frontend/dist
echo '<!DOCTYPE html><html><body>Test</body></html>' > frontend/dist/index.html

if ! go test -v -cover ./...; then
    echo "✗ GoCSV tests failed"
    cd ../..
    exit 1
fi
cd ../..

echo "✓ All core tests passed"

# Show coverage summary
echo ""
echo "=== Coverage Summary ==="
# One command per module. cmd/gocsv has its own go.mod, so naming it from the
# root module gives "main module does not contain package .../cmd/gocsv" and its
# coverage never appears at all -- which is how it has been printing for as long
# as the summary listed it alongside the root packages.
# shellcheck disable=SC2086
go test -cover $CORE_PACKAGES 2>/dev/null | grep -E "coverage:|ok" || true
(cd cmd/gocsv && go test -cover ./... 2>/dev/null | grep -E "coverage:|ok") || true

echo ""
echo "=== Core tests completed successfully ===" 