// GoPCA Suite
//
// Copyright © 2025-2026 Rune Mathisen <devel@bitjungle.com>
//
// This file is part of GoPCA Suite.
//
// GoPCA Suite is source-available software with free binary redistribution.
// Official compiled binary releases may be used and redistributed free of charge
// under the GoPCA Suite Source-Available Freeware License.
//
// The source code is provided for viewing, review, education, security analysis,
// research, interoperability analysis, and evaluation only.
//
// Modification, redistribution, publication, sublicensing, reuse, incorporation
// into another project, or creation of derivative works based on the source code
// is not permitted without prior written permission from the copyright holder.
//
// Usage Restriction: GoPCA Suite may not be used, directly or indirectly, for
// military, warfare, weapons, intelligence, surveillance, targeting, or
// law-enforcement surveillance applications.
//
// See LICENSE for the full license terms.

package core_test

import (
	"os"
	"path/filepath"
	"testing"
)

// requireReferences decides what to do when a reference file is absent.
//
// On a developer's machine, absent references mean Python and scikit-learn have
// not been run; skipping with instructions is the helpful answer, and demanding
// a venv from someone editing unrelated code is not.
//
// In CI it is the opposite. The workflow installs scikit-learn and generates
// every reference before the tests run, so a missing file there means the
// generation step has broken or a generator has been dropped from the list --
// and a skipped test prints no failure, so the coverage disappears without
// anything going red.
//
// That is not hypothetical. TestValidatePCRAgainstSklearn skipped on every CI
// run from the day it was written, because nobody added its generator to the
// workflow, and nothing reported it. The same was true of
// TestStudentTCDF_Validation. Both were found by reading the logs, not by a
// failure. Issue #845 asks for exactly this guard and this function is it.
func requireReferences(t *testing.T, what string, paths ...string) {
	t.Helper()

	var missing []string
	for _, path := range paths {
		if _, err := os.Stat(path); os.IsNotExist(err) {
			missing = append(missing, filepath.Base(path))
		}
	}
	if len(missing) == 0 {
		return
	}

	// GitHub Actions sets CI=true; so does essentially every other runner.
	if os.Getenv("CI") != "" {
		t.Fatalf("%s reference files are missing in CI: %v\n"+
			"They are generated by .github/workflows/build.yml before the tests run, "+
			"so this means the generation step failed or the generator was dropped "+
			"from that list. Skipping here would remove the validation silently, "+
			"which is how this comparison went unrun for months.", what, missing)
	}

	t.Skipf("%s reference files not found locally (%v). "+
		"Generate them with: make generate-sklearn-reference", what, missing)
}
