# GitHub Pages Configuration
title: GoPCA Suite - Liberating Your Data from Dimensional Oppression
description: Professional-grade PCA analysis tools. Data analysis for the people, by the people. No corporate clouds. No surveillance. No masters.
baseurl: "/gopca"
url: "https://bitjungle.github.io"

# Build settings
markdown: kramdown
theme: null  # We're using custom HTML/CSS

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock