name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering for testing

env:
  GO_VERSION: '1.21'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: |
        # Run tests for all packages except desktop (which requires frontend build)
        go test -v -cover ./internal/... ./pkg/... ./cmd/gopca-cli/...
    
    - name: Run linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m ./internal/... ./pkg/... ./cmd/gopca-cli/...

  build-cli:
    name: Build CLI
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Build all platforms
      run: make build-all
    
    - name: Upload CLI artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gopca-cli-binaries
        path: build/gopca-cli-*
        retention-days: 7

  build-desktop:
    name: Build Desktop App
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: darwin
          - os: windows-latest
            platform: windows
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: cmd/gopca-desktop/frontend/package-lock.json
    
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        # Check which webkit packages are available
        apt-cache search webkit2gtk | grep -E 'webkit2gtk-[0-9]' || true
        # Install the available webkit package
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev
    
    - name: Install frontend dependencies
      working-directory: cmd/gopca-desktop/frontend
      run: npm ci
    
    - name: Build desktop app
      working-directory: cmd/gopca-desktop
      shell: bash
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        wails build -platform ${{ matrix.platform }}
    
    - name: Upload desktop artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gopca-desktop-${{ matrix.platform }}
        path: |
          cmd/gopca-desktop/build/bin/*
          !cmd/gopca-desktop/build/bin/*.pdb
          !cmd/gopca-desktop/build/bin/*.ilk
        retention-days: 7